config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contacts
  resources :prefectures 
    resources :hotels do
      resources :reviews
      resources :reservations
    end
  root 'hotels#index'
  get 'hotels', to: 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
mount_uploader :picture, PictureUploader
  has_many :reviews
  has_many :reservations
  belongs_to :prefecture
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
mount_uploader :picture, PictureUploader
has_many :hotels
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hotel
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
        @contact = Contact.new
      end

      def create
        @contact = Contact.new(contact_params)

        if @contact.save
          redirect_to contact_path(@contact)
        end
      end

      def contact_params
        params.require(:contact).permit(:name, :content, :email)
      end

      def show
      @contact = Contact.find(params[:id])
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
  @hotels = Hotel.all
  @q = Hotel.ransack(params[:q])
  @hotels = @q.result(distinct: true)
  end
  def show
  @hotel = Hotel.find(params[:id])
  end
  def hotel_params
      params.require(:hotel).permit(:name, :picture, :description, :prefecture_id)
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def index
  @prefectures = Prefecture.all
   @q = Prefecture.ransack(params[:q])
  @prefectures = @q.result(distinct: true)
  end
  def show
  @prefecture = Prefecture.find(params[:id])
  @hotels = @prefecture.hotels
  end
def prefecture_params
  params.require(:prefecture).permit(:name)
end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
def new
  @hotel = Hotel.find(params[:hotel_id])
  @reservation = @hotel.reservations.build
end

def create
  @hotel = Hotel.find(params[:hotel_id])
  @reservation = Reservation.new(reservation_params)
  if @reservation.save
    redirect_to hotel_reservation_path(@hotel,@reservation)
  end
end

def reservation_params
  params.require(:reservation).permit(:name, :checkin, :checkout, :people, :hotel_id)
end
def show
  @hotel = Hotel.find(params[:hotel_id])
  @reservation = Reservation.find(params[:id])
end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @hotel = Hotel.find(params[:hotel_id])
    @reviews = @hotel.reviews
  end
  def new
    @hotel = Hotel.find(params[:hotel_id])
    @review = @hotel.reviews.build
  end
  def create
    @hotel = Hotel.find(params[:hotel_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to hotel_reviews_path(@hotel)
    end
  end

  def review_params
    params.require(:review).permit(:name, :title, :description, :hotel_id)
  end
  def edit
    @hotel = Hotel.find(params[:hotel_id])
    @review = Review.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:hotel_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to hotel_reviews_path(@hotel)
    end
  end
def show
  @hotel = Hotel.find(params[:hotel_id])
  @review = Review.find(params[:id])
end
  def destroy
    @hotel = Hotel.find(params[:hotel_id])
    @review = Review.find(params[:id])
    if @review.destroy
      redirect_to hotel_reviews_path(@hotel)
    end
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/contacts/new.html.erb
<h1>お問い合わせ</h1>

<%= form_with(model: @contact, local: true) do |form| %>
<!-- name -->
  <div class="field">
    <%= form.label :お名前 %>
    <%= form.text_field :name, id: :contact_name %>
  </div>
<!-- description -->
  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_area :content, id: :contact_content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/show.html.erb
<h1>お問い合わせ</h1>
<p><%= @contact.name %></p>
<p><%= @contact.content %></p>

app/views/hotels/_form.html.erb
<%= form.text_field :picture %>
<%= form.file_field :picture %>

app/views/hotels/index.html.erb
<h1>ホテルの一覧</h1>
<%= search_form_for @q do |f| %>

  
  <%= f.label :ホテル名 %>
  <%= f.search_field :name_cont %>
  <%= f.submit '検索', class: "btn btn-primary" %>
<% end %>


    <div class="container">
      <div class="row">
<% @hotels.each do |hotel| %>
        <div class="col-md-3">
          <div class="card">
            <img src="<%=hotel.picture_url%>" class="card-img-top" alt="<%=hotel.picture  %>">
            <div class="card-body">
              <h5 class="card-title"><%= hotel.name %></h5>
              <p class="card-text"><%= hotel.description %></p>
            </div>
            <div class="card-footer">
            <small class="text-muted"><%= link_to 'ホテルの詳細',hotel_path(hotel) %></small>
            </div>
          </div> 
        </div>
<% end %>
      </div>
    </div>

app/views/hotels/show.html.erb
<h1>ホテル詳細ページ</h1>
<div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="card">
            <img src="<%=@hotel.picture_url%>" class="card-img-top" alt="<%=@hotel.picture  %>">
            <div class="card-body">
              <h5 class="card-title"><%= @hotel.name %></h5>
              <p class="card-text"><%= @hotel.description %></p>
            </div>
            <div class="card-footer">
            <small class="text-muted"><%= link_to 'ホテルのレビューの一覧',hotel_reviews_path(@hotel) %></small>
            <small class="text-muted"><%= link_to 'レビュー投稿',new_hotel_review_path(@hotel) %></small>
            <small class="text-muted"><%= link_to '新規予約',new_hotel_reservation_path(@hotel) %></small>
            </div>
          </div> 
        </div>
      </div>
</div>

<%= link_to 'Back',hotels_path(@hotels) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <nav class="navbar navbar-expand-sm navbar-light">
          <a class="navbar-brand font-italic" href="/" style="font-size: 30px"><u>Hotel Project</u></a>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div id="menu" class="collapse navbar-collapse d-flex justify-content-end">
            <ul class="navbar-nav">
              <li class="nav-item"><a href="/" class="nav-link">トップページ</a></li>
              <li class="nav-item"><a href="/prefectures" class="nav-link">都道府県の一覧</a></li>
              <li class="nav-item"><a href="/contacts/new" class="nav-link">お問い合わせ</a></li>
            </ul>
          </div>
        </nav>  
      </div>
    </header>
    <%= yield %>
    <footer class="mt-5">
      <p class="text-center text-muted display-5 bg-light">Hotel Project</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/prefectures/_form.html.erb
<%= form.text_field :picture %>
<%= form.file_field :picture %>

app/views/prefectures/index.html.erb
<p>都道府県の一覧</p>
<%= search_form_for @q do |f| %>

<%= f.label :都道府県名 %>
  <%= f.search_field :name_cont %>
  <%= f.submit '検索', class: "btn btn-primary" %>
<% end %>
<div class="container">
      <div class="row">
<% @prefectures.each do |prefecture| %>
        <div class="col-md-3">
          <div class="card">
            <img src="<%=prefecture.picture_url%>" class="card-img-top" alt="<%=prefecture.picture  %>">
            <div class="card-body">
              <h5 class="card-title"><%= prefecture.name %></h5>
            </div>
            <div class="card-footer">
            <small class="text-muted"><%= link_to '詳細',prefecture_path(prefecture) %></small>
            </div>
          </div> 
        </div>
 <% end %>
 </div>
    </div>

app/views/prefectures/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @prefecture.name %>
</p>
<%= image_tag(@prefecture.picture_url, width: 600) if @prefecture.picture.present? %>
<p>ホテルの一覧</p>
<div class="container">
      <div class="row">
<% @hotels.each do |hotel| %>
        <div class="col-md-3">
          <div class="card">
            <img src="<%=hotel.picture_url%>" class="card-img-top" alt="<%=hotel.picture  %>">
            <div class="card-body">
              <h5 class="card-title"><%= hotel.name %></h5>
              <p class="card-text"><%= hotel.description %></p>
            </div>
            <div class="card-footer">
            <%= link_to '詳細を見る', hotel_path(hotel) %>
            <%= link_to 'レビューを見る', hotel_reviews_path(hotel) %>
            </div>
          </div> 
        </div>
<% end %>
      </div>
    </div>

<%= link_to 'Back', prefectures_path(@prefecture) %>

app/views/reservations/_form.html.erb
<%= form_with(model: [@hotel, reservation], local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :氏名　%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :チェックイン %>
    <%= form.text_field :checkin %>
  </div>

  
  <div class="field">
    <%= form.label :チェックアウト %>
    <%= form.text_field :checkout %>
  </div>

  
  <div class="field">
    <%= form.label :人数 %>
    <%= form.text_field :people %>
  </div>
<%= form.hidden_field :hotel_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>




app/views/reservations/new.html.erb
<h1>新規予約</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', hotel_reservations_path %>


app/views/reservations/show.html.erb
<h1>ご予約ありがとうございます。</h1>
<p id="notice"><%= notice %></p>



<div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= @hotel.name %></h5>
              <h5 class="card-title"><%= @reservation.name %></h5>
              <h5 class="card-title"><%= @reservation.checkin %></h5>
              <h5 class="card-title"><%= @reservation.checkout %></h5>
              <h5 class="card-title"><%= @reservation.people %></h5>
            </div>
            <div class="card-footer">
            </div>
          </div> 
        </div>
      </div>
</div>

<%= link_to 'Back', 
new_hotel_reservation_path(@hotel) %>

app/views/reviews/_form.html.erb
<%= form_with(model: [@hotel, review], local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
<%= form.hidden_field :hotel_id %>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
<%= form.hidden_field :hotel_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<div class="field">
<% end %>





app/views/reviews/index.html.erb
<p>ホテルのレビューの一覧</p>
<div class="container">
      <div class="row">
<% @reviews.each do |review| %>
        <div class="col-md-3">
          <div class="card">
            <img src="<%=@hotel.picture_url%>" class="card-img-top" alt="<%=@hotel.picture  %>">
            <div class="card-body">
              <h5 class="card-title"><%= review.title %></h5>
              <h5 class="card-title"><%= review.name %></h5>
              <p class="card-text"><%= review.description %></p>
            </div>
            <div class="card-footer">
            <small class="text-muted"><%= link_to 'レビューの詳細',hotel_review_path(@hotel,review) %></small>
            </div>
          </div> 
        </div>
<% end %>
      </div>
    </div>
<%= link_to 'Back',hotel_path(@hotel) %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', hotel_reviews_path %>



app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Back', hotel_reviews_path(@hotel) %>
<div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="card">
            <img src="<%=@hotel.picture_url%>" class="card-img-top" alt="<%=@hotel.picture  %>">
            <div class="card-body">
              <h5 class="card-title"><%= @hotel.name %></h5>
              <h5 class="card-title"><%= @review.name %></h5>
              <h5 class="card-title"><%= @review.title %></h5>
              <p class="card-text"><%= @review.description %></p>
            </div>
            <div class="card-footer">
            <small class="text-muted"><%= link_to 'Back', hotel_reviews_path(@hotel) %></small>
            </div>
          </div> 
        </div>
      </div>
</div>